### ISSUE TITLE
Cannot rename overlay in VR

### ISSUE THREAD

**Issue by Phoenix616** [elvissteinjr/DesktopPlus#17] opened 2021-03-23 20:32 UTC
When trying to rename an overlay it is not possible to type anything or get it to remove the input view. The program gets stuck on that screen and needs to be stopped and some config file deleted for it to get out of that state.

Version: 2.4.6 Beta

**Comment by elvissteinjr** [comment] 2021-03-23 20:53
I can confirm the rename popup (and other popups) being displayed where they shouldn't be in VR. Pressing enter on the VR keyboard does close the popup on my end at least (but breaks further UI keyboard interaction, another issue I guess). Cannot reproduce having to reset the config to get out of it, though.
Renaming via right-clicking the drop-down selection or switching into desktop mode from the tray icon should also still work as an alternative in the meantime.

Considering what I meant to fix in that build this is pretty embarrassing, but I'll get to it. Need to be more careful. Thanks for the report.

**Comment by elvissteinjr** [comment] 2021-03-23 22:25
Both should be fixed in code now. Next build with the fix will be next the stable version though. Should still land this week if nothing terrible comes up. 
The keyboard enter issue has always been broken, funnily enough. All the way back to v2.0 when the UI was introduced.

Thanks again.

**Closed by elvissteinjr** 2021-03-23 22:25 UTC

**Comment by Phoenix616** [comment] 2021-03-23 22:34
Awesome, thanks for the very fast fix! (And the tipp for possible workarounds)
