### ISSUE TITLE
[NewUI] No longer accepts mouse clicks or other mouse actions during ingame.

### ISSUE THREAD

**Issue by ni1chigo2115** [elvissteinjr/DesktopPlus#46] opened 2022-10-07 03:53 UTC
With this NewUI update, it seems that even if you accept mouse operations during ingame, the mouse position is synchronized, but it no longer accepts mouse operations such as left/right clicks and wheel.

**Comment by elvissteinjr** [comment] 2022-10-08 00:38
I can't reproduce this on my end, works fine here.
Were you using the NewUI builds before? If not, then the controller bindings may not have the necessary inputs bound if you set up global shortcuts in a stable branch build at some point.

If that's not it, what controllers are you using? Do the controller bindings for Desktop+ look correct?
Can you confirm that it works in the previous NewUI Preview build?

**Comment by ni1chigo2115** [comment] 2022-10-11 02:57
Apparently, the setting that allows interference with the overlay during ingame is itself being ignored: if you pull the trigger while the VRC menu is on, the menu on the VRC side works.

**Comment by elvissteinjr** [comment] 2022-10-11 16:09
> Apparently, the setting that allows interference with the overlay during ingame is itself being ignored: if you pull the trigger while the VRC menu is on, the menu on the VRC side works.

I believe this has more to do with how the laser pointer inputs don't work. The input blocking has never been absolute but instead blocks for any input that is bound for the laser pointer. This particular behavior is handled in SteamVR itself and can't really be influenced from the overlay end (aside from choosing to fully opt out).

There's a [thread on the Steam forums](https://steamcommunity.com/app/1494460/discussions/3/3385042609889958858/) about this issue now as well. Are there any parallels with that user that you notice?
Custom input driver in use there and the last stable SteamVR update being released within days of the current Desktop+ build make for a shaky foundation.

Just to make sure, did you use NewUI Preview 7 with the current SteamVR version and did it work there? Could you take a look again with that version if not?
This one's a bit hard for me to debug as it appears to work as intended with Index Controllers, which is all I have at hand right now.

**Closed** 2023-10-24 11:16 UTC
